import { useState } from 'react';
import { Alert, Switch, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Button, Card, Chips, Empty, Field, Label, Pill, RowLink, Screen, useUI } from '../components/ui';
import { makeId, products, useDemo } from '../demo/DemoProvider';
import { wholeNumber } from '../demo/forms';
import { useManagement, type Role, type Staff } from './ManagementProvider';
import { ManagementNotice } from './navigation';

export function AdminHome() {
  const m = useManagement(); const { tx } = useUI();
  return <Screen title={tx('Admin overview', 'نظرة مدير النظام')} subtitle={tx('VOLTEX · Organization workspace', 'فولتكس · مساحة المؤسسة')}><ManagementNotice /><Card tinted><Pill text={tx('ORGANIZATION', 'المؤسسة')} /><Label bold size={32}>{m.state.staff.filter(u => u.active).length} {tx('active accounts', 'حسابات نشطة')}</Label><Label>{m.state.branches.filter(b => b.active).length} {tx('active branches', 'فروع نشطة')} · {m.state.catalog.length} {tx('catalog items', 'منتجات بالكتالوج')}</Label><Button title={tx('Create demo account', 'إنشاء حساب تجريبي')} onPress={() => router.push('/admin/user')} /></Card><Card><RowLink icon="user" title={tx('Users & assignments', 'الحسابات والتكليفات')} onPress={() => router.push('/admin/users')} /><RowLink icon="pin" title={tx('Manage branches', 'إدارة الفروع')} onPress={() => router.push('/admin/branches')} /><RowLink icon="reward" title={tx('Branch targets', 'مستهدفات الفروع')} onPress={() => router.push('/admin/targets')} /><RowLink icon="sales" title={tx('Organization reports', 'تقارير المؤسسة')} onPress={() => router.push('/admin/reports')} /></Card><Card><RowLink icon="request" title={tx('Recent changes', 'آخر التغييرات')} detail={`${m.state.audit.length} ${tx('local audit events', 'أحداث مراجعة محلية')}`} onPress={() => router.push('/admin/audit')} /></Card></Screen>;
}
export function UsersScreen() {
  const m = useManagement(); const { tx } = useUI(); const { state } = useDemo(); const [search, setSearch] = useState(''); const [filter, setFilter] = useState<'all' | Role>('all');
  const list = m.state.staff.filter(u => (filter === 'all' || u.role === filter) && `${u.name} ${u.email}`.toLowerCase().includes(search.toLowerCase()));
  return <Screen title={tx('Users', 'الحسابات')} action={{ icon: 'plus', label: tx('Create user', 'إنشاء حساب'), run: () => router.push('/admin/user') }}><ManagementNotice /><Field label={tx('Search name or email', 'ابحث بالاسم أو البريد')} value={search} onChangeText={setSearch} /><Chips value={filter} onChange={setFilter} options={[{ value: 'all', label: tx('All', 'الكل') }, { value: 'promoter', label: tx('Promoters', 'المروّجون') }, { value: 'supervisor', label: tx('Supervisors', 'المشرفون') }, { value: 'admin', label: tx('Admins', 'المديرون') }]} />{!list.length && <Empty title={tx('No users match', 'لا توجد حسابات مطابقة')} detail={tx('Try another search or create an account.', 'جرّب بحثًا آخر أو أنشئ حسابًا.')} />}{list.map(u => <Card key={u.id}><RowLink icon="user" title={u.id === 'u1' ? state.profile.name : u.name} detail={`${u.email} · ${u.role}`} badge={u.active ? tx('Active', 'نشط') : tx('Inactive', 'معطّل')} onPress={() => router.push({ pathname: '/admin/user', params: { id: u.id } })} /></Card>)}<Button title={tx('Create demo account', 'إنشاء حساب تجريبي')} onPress={() => router.push('/admin/user')} /></Screen>;
}
export function UserEditor() {
  const { id } = useLocalSearchParams<{ id?: string }>(); const m = useManagement(); const demo = useDemo(); const { tx, row } = useUI(); const existing = m.state.staff.find(u => u.id === id);
  const [name, setName] = useState(existing?.id === 'u1' ? demo.state.profile.name : existing?.name ?? ''); const [email, setEmail] = useState(existing?.email ?? ''); const [role, setRole] = useState<Role>(existing?.role ?? 'promoter'); const [branchId, setBranch] = useState(existing?.branchId ?? 'b1'); const [supervisorId, setSupervisor] = useState(existing?.supervisorId ?? 's1'); const [active, setActive] = useState(existing?.active ?? true); const [error, setError] = useState('');
  const fixed = ['u1', 's1', 'a1'].includes(id ?? '');
  if (id && !existing) return <Screen back title={tx('Account', 'الحساب')}><Empty title={tx('Account unavailable', 'الحساب غير متاح')} detail={tx('Choose an account from Users.', 'اختر حسابًا من قائمة الحسابات.')} /><Button title={tx('Users', 'الحسابات')} onPress={() => router.replace('/admin/users')} /></Screen>;
  function save() {
    if (name.trim().length < 2 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()) || m.state.staff.some(u => u.id !== id && u.email.toLowerCase() === email.trim().toLowerCase())) { setError(tx('Enter a name and a unique valid email.', 'أدخل اسمًا وبريدًا صحيحًا غير مستخدم.')); return; }
    if (active && !m.state.branches.some(b => b.id === branchId && b.active)) { setError(tx('Choose an active branch.', 'اختر فرعًا نشطًا.')); return; }
    if (role === 'promoter' && !m.state.staff.some(u => u.id === supervisorId && u.role === 'supervisor' && u.active)) { setError(tx('Assign an active supervisor.', 'حدّد مشرفًا نشطًا.')); return; }
    if (existing?.role === 'supervisor' && (!active || role !== 'supervisor') && m.state.staff.some(u => u.supervisorId === id && u.active)) { setError(tx('Reassign this supervisor’s active team first.', 'أعد إسناد فريق المشرف النشط أولًا.')); return; }
    if (existing?.role === 'admin' && existing.active && (!active || role !== 'admin') && m.state.staff.filter(u => u.role === 'admin' && u.active).length <= 1) { setError(tx('Keep at least one active administrator.', 'يجب وجود مدير نشط واحد على الأقل.')); return; }
    const user: Staff = { id: id ?? makeId('U'), name: name.trim(), email: email.trim().toLowerCase(), role, branchId, supervisorId: role === 'promoter' ? supervisorId : '', active };
    m.change(`${id ? 'Updated' : 'Created'} account: ${user.name}`, s => ({ ...s, staff: id ? s.staff.map(u => u.id === id ? user : u) : [...s.staff, user] }));
    if (id === 'u1') demo.update(s => ({ ...s, profile: { ...s.profile, name: user.name } })); router.replace('/admin/users');
  }
  return <Screen back title={existing ? tx('Edit account', 'تعديل الحساب') : tx('Create account', 'إنشاء حساب')}><ManagementNotice /><Card tinted><Label>{tx('Directory record only. This does not create login credentials or send an invitation.', 'سجل بالدليل فقط. لا ينشئ بيانات دخول ولا يرسل دعوة.')}</Label></Card><Field label={tx('Name', 'الاسم')} value={name} onChangeText={setName} maxLength={60} /><Field label={tx('Email', 'البريد')} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" />
    {fixed ? <Card><Label bold>{tx('Linked demo identity', 'هوية تجريبية مرتبطة')}</Label><Label>{tx('Role, branch and activation are fixed for this preview identity. Use a new account to explore assignments.', 'الدور والفرع والتفعيل ثابتة لهذه الهوية المرتبطة. استخدم حسابًا جديدًا لاستكشاف التكليفات.')}</Label></Card> : <><Label bold>{tx('Role', 'الدور')}</Label><Chips value={role} onChange={setRole} options={[{ value: 'promoter', label: tx('Promoter', 'مروّج') }, { value: 'supervisor', label: tx('Supervisor', 'مشرف') }, { value: 'admin', label: tx('Admin', 'مدير') }]} /><Label bold>{tx('Branch', 'الفرع')}</Label><Chips value={branchId} onChange={setBranch} options={m.state.branches.filter(b => b.active || b.id === branchId).map(b => ({ value: b.id, label: b.name }))} />{role === 'promoter' && <><Label bold>{tx('Supervisor', 'المشرف')}</Label><Chips value={supervisorId} onChange={setSupervisor} options={m.state.staff.filter(u => u.role === 'supervisor' && u.active).map(u => ({ value: u.id, label: u.name }))} /></>}<View style={[row, { alignItems: 'center', justifyContent: 'space-between' }]}><Label>{tx('Account active', 'الحساب نشط')}</Label><Switch accessibilityLabel={tx('Account active', 'الحساب نشط')} value={active} onValueChange={setActive} /></View></>}
    {!!error && <Label>{error}</Label>}<Button title={tx('Save account locally', 'حفظ الحساب محليًا')} onPress={save} />
  </Screen>;
}
export function BranchesScreen() {
  const m = useManagement(); const { tx } = useUI(); const [search, setSearch] = useState(''); const list = m.state.branches.filter(b => `${b.name} ${b.address}`.toLowerCase().includes(search.toLowerCase()));
  return <Screen title={tx('Branches', 'الفروع')} action={{ icon: 'plus', label: tx('Add branch', 'إضافة فرع'), run: () => router.push('/admin/branch') }}><ManagementNotice /><Field label={tx('Search branches', 'ابحث عن فرع')} value={search} onChangeText={setSearch} />{!list.length && <Empty title={tx('No matching branches', 'لا توجد فروع مطابقة')} detail={tx('Try another name or add a branch.', 'جرّب اسمًا آخر أو أضف فرعًا.')} />}{list.map(b => <Card key={b.id}><RowLink icon="pin" title={b.name} detail={`${b.address} · ${m.state.staff.filter(u => u.branchId === b.id).length} ${tx('accounts', 'حسابات')}`} badge={b.active ? tx('Active', 'نشط') : tx('Inactive', 'معطّل')} onPress={() => router.push({ pathname: '/admin/branch', params: { id: b.id } })} /></Card>)}<Button title={tx('Add branch', 'إضافة فرع')} onPress={() => router.push('/admin/branch')} /></Screen>;
}
export function BranchEditor() {
  const { id } = useLocalSearchParams<{ id?: string }>(); const m = useManagement(); const { tx, row } = useUI(); const item = m.state.branches.find(b => b.id === id); const [name, setName] = useState(item?.name ?? ''); const [address, setAddress] = useState(item?.address ?? ''); const [active, setActive] = useState(item?.active ?? true); const [error, setError] = useState('');
  if (id && !item) return <Screen back title={tx('Branch unavailable', 'الفرع غير متاح')}><Button title={tx('Branches', 'الفروع')} onPress={() => router.replace('/admin/branches')} /></Screen>;
  function save() { if (name.trim().length < 2 || address.trim().length < 4 || m.state.branches.some(b => b.id !== id && b.name.toLowerCase() === name.trim().toLowerCase())) { setError(tx('Enter a unique branch name and address.', 'أدخل اسم فرع غير مكرر وعنوانًا واضحًا.')); return; } if (!active && m.state.staff.some(u => u.branchId === id && u.active)) { setError(tx('Reassign active staff before deactivating this branch.', 'انقل الموظفين النشطين قبل تعطيل الفرع.')); return; } const branch = { id: id ?? makeId('B'), name: name.trim(), address: address.trim(), active }; m.change(`Branch saved: ${branch.name}`, s => ({ ...s, branches: id ? s.branches.map(b => b.id === id ? branch : b) : [...s.branches, branch] })); router.replace('/admin/branches'); }
  return <Screen back title={item ? tx('Branch details', 'تفاصيل الفرع') : tx('Add branch', 'إضافة فرع')}><ManagementNotice />{id === 'b1' && <Card tinted><Label>{tx('The linked Citystars branch identity is fixed while promoter data uses the sample assignment.', 'هوية فرع سيتي ستارز ثابتة أثناء ربط بيانات المروّج بالتكليف التجريبي.')}</Label></Card>}<Field label={tx('Branch name', 'اسم الفرع')} value={name} onChangeText={setName} editable={id !== 'b1'} maxLength={80} /><Field label={tx('Address', 'العنوان')} value={address} onChangeText={setAddress} multiline maxLength={200} /><View style={[row, { alignItems: 'center', justifyContent: 'space-between' }]}><Label>{tx('Branch active', 'الفرع نشط')}</Label><Switch accessibilityLabel={tx('Branch active', 'الفرع نشط')} value={active} onValueChange={setActive} disabled={id === 'b1'} /></View>{!!error && <Label>{error}</Label>}<Button title={tx('Save branch', 'حفظ الفرع')} onPress={save} />{item && <Card><Label bold>{tx('Assigned accounts', 'الحسابات المسندة')}</Label>{m.state.staff.filter(u => u.branchId === id).map(u => <RowLink key={u.id} title={u.name} icon="user" onPress={() => router.push({ pathname: '/admin/user', params: { id: u.id } })} />)}</Card>}</Screen>;
}
export function CatalogScreen() {
  const m = useManagement(); const { tx, money } = useUI(); const [search, setSearch] = useState(''); const list = m.state.catalog.filter(p => `${p.name} ${p.sku}`.toLowerCase().includes(search.toLowerCase()));
  return <Screen title={tx('Catalog management', 'إدارة الكتالوج')} action={{ icon: 'plus', label: tx('Add product', 'إضافة منتج'), run: () => router.push('/admin/product') }}><ManagementNotice /><Card tinted><Label>{tx('Planning catalog. Publishing to promoter sales and stock will be connected with the backend; existing sale prices are unchanged.', 'كتالوج تخطيطي. نشره لمبيعات ومخزون المروّج سيتم مع الخادم؛ أسعار العمليات الحالية لا تتغير.')}</Label></Card><Field label={tx('Find a product or SKU', 'ابحث عن منتج أو كود')} value={search} onChangeText={setSearch} />{!list.length && <Empty title={tx('No products match', 'لا توجد منتجات مطابقة')} detail={tx('Try another search or add a product.', 'جرّب بحثًا آخر أو أضف منتجًا.')} />}{list.map(p => <Card key={p.id}><RowLink icon="stock" title={p.name} detail={`${p.sku} · ${money(p.price)}`} badge={p.active ? tx('Active', 'نشط') : tx('Archived', 'مؤرشف')} onPress={() => router.push({ pathname: '/admin/product', params: { id: p.id } })} /></Card>)}<Button title={tx('Add product', 'إضافة منتج')} onPress={() => router.push('/admin/product')} /></Screen>;
}
export function ProductEditor() {
  const { id } = useLocalSearchParams<{ id?: string }>(); const m = useManagement(); const { tx, row } = useUI(); const p = m.state.catalog.find(p => p.id === id); const [name, setName] = useState(p?.name ?? ''); const [sku, setSku] = useState(p?.sku ?? ''); const [price, setPrice] = useState(String(p?.price ?? '')); const [active, setActive] = useState(p?.active ?? true); const [error, setError] = useState('');
  if (id && !p) return <Screen back title={tx('Product unavailable', 'المنتج غير متاح')}><Button title={tx('Catalog', 'الكتالوج')} onPress={() => router.replace('/admin/catalog')} /></Screen>;
  function save() { const amount = wholeNumber(price); if (name.trim().length < 2 || !/^[A-Za-z0-9-]{2,30}$/.test(sku) || !Number.isSafeInteger(amount) || amount < 1 || amount > 10000000 || m.state.catalog.some(p => p.id !== id && p.sku.toLowerCase() === sku.toLowerCase())) { setError(tx('Enter a name, unique alphanumeric SKU and whole EGP price from 1 to 10,000,000.', 'أدخل اسمًا وكودًا لاتينيًا غير مكرر وسعرًا صحيحًا من 1 إلى 10,000,000 جنيه.')); return; } const product = { id: id ?? makeId('SKU'), name: name.trim(), sku: sku.toUpperCase(), price: amount, active }; m.change(`Catalog saved: ${product.sku}`, s => ({ ...s, catalog: id ? s.catalog.map(p => p.id === id ? product : p) : [...s.catalog, product] })); router.replace('/admin/catalog'); }
  return <Screen back title={p ? tx('Edit product', 'تعديل المنتج') : tx('Add product', 'إضافة منتج')}><ManagementNotice /><Field label={tx('Product name', 'اسم المنتج')} value={name} onChangeText={setName} maxLength={80} /><Field label="SKU" value={sku} onChangeText={setSku} autoCapitalize="characters" /><Field label={tx('Price · EGP', 'السعر · جنيه')} value={price} onChangeText={setPrice} keyboardType="number-pad" /><View style={[row, { alignItems: 'center', justifyContent: 'space-between' }]}><Label>{tx('Product active', 'المنتج نشط')}</Label><Switch accessibilityLabel={tx('Product active', 'المنتج نشط')} value={active} onValueChange={setActive} /></View>{!!error && <Label>{error}</Label>}<Button title={tx('Save catalog draft', 'حفظ مسودة الكتالوج')} onPress={save} /></Screen>;
}
export function TargetsScreen() {
  const m = useManagement(); const { tx, money } = useUI(); const [branch, setBranch] = useState('b1'); const [amount, setAmount] = useState(String(m.state.targets.b1 ?? 0)); const [message, setMessage] = useState('');
  return <Screen back title={tx('Daily branch targets', 'المستهدفات اليومية للفروع')}><ManagementNotice /><Chips value={branch} onChange={b => { setBranch(b); setAmount(String(m.state.targets[b] ?? 0)); setMessage(''); }} options={m.state.branches.filter(b => b.active).map(b => ({ value: b.id, label: b.name }))} /><Card tinted><Label>{tx('Current daily target', 'المستهدف اليومي الحالي')}</Label><Label bold size={28}>{money(m.state.targets[branch] ?? 0)}</Label></Card><Field label={tx('Daily target · EGP', 'المستهدف اليومي · جنيه')} value={amount} onChangeText={setAmount} keyboardType="number-pad" /><Label muted>{tx('Citystars updates the promoter dashboard in this demo. Other targets are planning values.', 'سيتي ستارز يحدّث لوحة المروّج في التجربة. باقي المستهدفات قيم تخطيطية.')}</Label>{!!message && <Label>{message}</Label>}<Button title={tx('Save target', 'حفظ المستهدف')} onPress={() => { const n = wholeNumber(amount); if (!Number.isSafeInteger(n) || n < 1 || n > 100000000) { setMessage(tx('Enter a whole target from 1 to 100,000,000.', 'أدخل مستهدفًا صحيحًا من 1 إلى 100,000,000.')); return; } m.change(`Daily target ${branch}: ${n}`, s => ({ ...s, targets: { ...s.targets, [branch]: n } })); setMessage(tx('Target saved locally.', 'تم حفظ المستهدف محليًا.')); }} /></Screen>;
}
export function AuditScreen() {
  const m = useManagement(); const { tx, date } = useUI(); const [filter, setFilter] = useState<'all' | Role>('all'); const list = m.state.audit.filter(e => filter === 'all' || e.actor === filter);
  return <Screen back title={tx('Audit history', 'سجل التغييرات')} subtitle={tx('Latest 500 local events · not a server audit trail', 'آخر 500 حدث محلي · ليس سجلًا رقابيًا على الخادم')}><ManagementNotice /><Chips value={filter} onChange={setFilter} options={[{ value: 'all', label: tx('All', 'الكل') }, { value: 'admin', label: tx('Admin', 'مدير') }, { value: 'supervisor', label: tx('Supervisor', 'مشرف') }, { value: 'promoter', label: tx('Promoter', 'مروّج') }]} />{!list.length && <Empty title={tx('No changes recorded', 'لا توجد تغييرات مسجلة')} detail={tx('Account edits, reviews and assignments appear here.', 'تظهر تعديلات الحسابات والمراجعات والتكليفات هنا.')} />}{list.map(e => <Card key={e.id}><Pill text={e.actor} /><Label>{e.action}</Label><Label muted size={12}>{date(e.date)}</Label></Card>)}</Screen>;
}
export function AccessScreen() {
  const { tx } = useUI();
  return <Screen back title={tx('Roles & access', 'الأدوار والصلاحيات')}><Card tinted><Label>{tx('This is the planned access model. Role selection in the demo is not security enforcement.', 'هذا نموذج الصلاحيات المخطط. اختيار الدور في التجربة ليس حماية أمنية.')}</Label></Card><Card><Label bold size={20}>{tx('Promoter', 'المروّج')}</Label><Label>{tx('Own sales, attendance, requests and assigned branch inventory. No account management or self-approval.', 'مبيعاته وحضوره وطلباته ومخزون فرعه المسند. بدون إدارة حسابات أو اعتماد ذاتي.')}</Label></Card><Card><Label bold size={20}>{tx('Supervisor', 'المشرف')}</Label><Label>{tx('Assigned team only: review linked requests/photos, assign tasks and view team reports.', 'الفريق المسند فقط: مراجعة الطلبات والصور وإسناد المهام ومتابعة التقارير.')}</Label></Card><Card><Label bold size={20}>{tx('Admin', 'مدير النظام')}</Label><Label>{tx('Manage accounts, branches, catalog, assignments, targets and audit history. Backend policies must validate every operation.', 'إدارة الحسابات والفروع والكتالوج والتكليفات والمستهدفات وسجل التغييرات. سياسات الخادم يجب أن تتحقق من كل عملية.')}</Label></Card></Screen>;
}
export function AdminReports() {
  const m = useManagement(); const { state } = useDemo(); const { tx, money } = useUI(); const [branch, setBranch] = useState('b1');
  return <Screen back title={tx('Organization reports', 'تقارير المؤسسة')}><ManagementNotice /><Chips value={branch} onChange={setBranch} options={m.state.branches.map(b => ({ value: b.id, label: b.name }))} /><Card tinted><Label bold size={25}>{m.state.branches.find(b => b.id === branch)?.name}</Label><Label>{m.state.staff.filter(u => u.branchId === branch && u.active).length} {tx('active accounts', 'حسابات نشطة')}</Label><Label>{tx('Daily target', 'المستهدف اليومي')}: {money(m.state.targets[branch] ?? 0)}</Label></Card>{branch === 'b1' ? <Card><Label bold>{tx('All linked demo sales', 'كل المبيعات التجريبية المرتبطة')}</Label><Label size={30} bold>{money(state.sales.reduce((n, s) => n + s.quantity * (products.find(p => p.id === s.productId)?.price ?? 0), 0))}</Label><Label>{state.requests.filter(r => r.status === 'pending').length} {tx('pending requests', 'طلبات قيد المراجعة')}</Label><Label>{state.photos.length} {tx('local photos', 'صور محلية')}</Label></Card> : <Empty title={tx('No linked operational records', 'لا توجد سجلات تشغيلية مرتبطة')} detail={tx('This branch currently has directory and planning data only.', 'هذا الفرع يحتوي حاليًا على بيانات الدليل والتخطيط فقط.')} />}</Screen>;
}
